import type { Passage, Question } from '../types';
export const diagnosticPassages:Passage[]=[
 {id:'diag-r1',theme:'training',level:'B',title:'Une séance d’information',text:'Une séance sur le nouvel outil de congés aura lieu mardi à 10 h. Elle est ouverte à tous les employés. Les personnes qui ne peuvent pas y assister recevront un enregistrement mercredi. Pour poser une question à l’avance, écrivez à l’équipe administrative avant lundi midi. Aucune inscription n’est nécessaire.'},
 {id:'diag-r2',theme:'projects',level:'C',title:'Interpréter les résultats',text:'Le nombre de dossiers clos a augmenté depuis la réorganisation. Ce constat mérite d’être salué, sans être assimilé à une preuve suffisante d’amélioration du service. La proportion de dossiers simples a elle aussi progressé. Une comparaison à complexité égale permettrait de mieux apprécier l’effet de la nouvelle organisation, tout en tenant compte de la satisfaction des usagers.'}];
const r=(id:string,level:'B'|'C',objective:string,prompt:string,options:string[],answer:number,explanations:string[]):Question=>({id,theme:level==='B'?'training':'projects',skill:'reading',level,objective,prompt,options,answer,explanations,passageId:level==='B'?'diag-r1':'diag-r2',diagnostic:true});
const w=(id:string,level:'B'|'C',objective:string,prompt:string,options:string[],answer:number,explanations:string[]):Question=>({id,theme:'teamwork',skill:'writing',level,objective,prompt,options,answer,explanations,diagnostic:true});
export const diagnosticQuestions:Question[]=[
 r('diag-q1','B','Explicit meaning','Quand faut-il envoyer une question à l’avance?',['Avant lundi midi.','Mercredi matin.','Après la séance.'],0,['This is the stated advance-question deadline.','Wednesday is when the recording is sent.','That would not be a question sent in advance.']),
 r('diag-q2','B','Main idea','Quel est le but du message?',['Annoncer une inscription obligatoire.','Informer les employés d’une séance et de ses modalités.','Présenter une politique de promotion.'],1,['The text says no registration is necessary.','The message gives the session, access, recording, and question arrangements.','Promotion is not discussed.']),
 r('diag-q3','B','Inference','Une personne absente mardi pourra-t-elle consulter le contenu?',['Non, aucun accès ultérieur n’est prévu.','Seulement si elle s’inscrit.','Oui, grâce à l’enregistrement.'],2,['A recording is explicitly promised.','The text says registration is unnecessary.','The recording is sent to those who cannot attend.']),
 r('diag-q4','C','Explicit meaning','Quel autre changement accompagne la hausse des dossiers clos?',['Une baisse certaine de satisfaction.','Une hausse de la proportion de dossiers simples.','La suppression de tous les dossiers complexes.'],1,['Satisfaction is to be considered; no decline is stated.','The text explicitly names this change in the case mix.','An increased share of simple cases does not mean all complex cases disappeared.']),
 r('diag-q5','C','Main idea','Que recommande le texte?',['Comparer des dossiers de complexité égale et considérer la satisfaction.','Évaluer uniquement le nombre total de dossiers clos.','Abandonner toute évaluation.'],0,['These two elements form the proposed fuller evaluation.','The author says the total alone is insufficient.','The author recommends a better evaluation, not abandoning it.']),
 r('diag-q6','C','Tone and nuance','Comment l’auteur considère-t-il le résultat?',['Comme une preuve définitive de succès.','Comme un échec certain.','Comme un signe positif qui demande une analyse plus fine.'],2,['“Sans être assimilé à une preuve suffisante” rules that out.','“Mérite d’être salué” recognizes something positive.','The text combines recognition with a call for a controlled comparison.']),
 w('diag-q7','B','Verb forms','Demain, vous ___ le nouveau formulaire.',['recevrons','recevrez','recevront'],1,['Recevrons agrees with nous.','Recevrez is the future form for vous.','Recevront agrees with ils or elles.']),
 w('diag-q8','B','Agreement','Les demandes sont ___.',['complet','complète','complètes'],2,['Masculine singular does not agree with demandes.','The noun is plural, so the adjective must be plural.','Complètes agrees with feminine plural demandes.']),
 w('diag-q9','B','Prepositions','Merci de participer ___ la rencontre.',['à','de','envers'],0,['Participer à is the required construction.','Participer de has a different literary meaning and does not express attending this meeting.','Envers is not used with participer.']),
 w('diag-q10','C','Subjunctive','Il faut que nous ___ prêts.',['sommes','serons','soyons'],2,['Sommes is indicative.','Serons is future indicative.','Il faut que requires the subjunctive soyons.']),
 w('diag-q11','C','Pronouns','Voici le dossier ___ elle est responsable.',['que','dont','où'],1,['Être responsable de requires a de relative, not que.','Dont replaces de ce dossier.','Où refers to a place or time.']),
 w('diag-q12','C','Agreement','Les notes que vous avez ___ sont utiles.',['rédigées','rédigé','rédigés'],0,['The preceding direct object notes is feminine plural.','Agreement is required when the direct object precedes avoir.','Notes is feminine, not masculine.'])];
