import type { Passage, Question, ThemeId, Level } from '../types';
type Check = [string,string,string,string,string,string,string];
// Each option has its own explanation. Correct options are rotated deterministically.
const passages: Passage[]=[]; const questions: Question[]=[];
function add(theme:ThemeId,level:Level,title:string,text:string,checks:Check[]){
 const id=`r-${theme}-${passages.filter(p=>p.theme===theme).length+1}`;passages.push({id,theme,level,title,text});
 checks.forEach(([prompt,correct,why,bad1,why1,bad2,why2],i)=>{const shift=(passages.length+i)%3;const opts=[correct,bad1,bad2];const ex=[why,why1,why2];for(let k=0;k<shift;k++){opts.push(opts.shift()!);ex.push(ex.shift()!)}questions.push({id:`${id}-q${i+1}`,theme,level,skill:'reading',objective:i===0?'Explicit meaning':i===1?'Main idea':level==='C'?'Tone and nuance':'Inference',passageId:id,prompt,options:opts,explanations:ex,answer:(3-shift)%3})});
}
add('training','B','Une place à confirmer',`Bonjour, il reste quatre places à l’atelier de rédaction claire du 18 octobre. Pour vous inscrire, faites approuver votre demande par votre gestionnaire, puis transmettez-la à l’équipe de formation avant vendredi. L’atelier est offert en ligne. Les personnes inscrites recevront le lien de connexion la veille. Aucun déplacement n’est nécessaire.`,[
 ['Que faut-il faire avant de transmettre la demande?','Obtenir l’accord de son gestionnaire.','“Faites approuver… puis transmettez-la” gives the required order.','Recevoir le lien de connexion.','The link arrives the day before the workshop, after registration.','Réserver un déplacement.','“Aucun déplacement” explicitly rules this out.'],
 ['Quel est le but principal du message?','Expliquer comment s’inscrire à un atelier.','The message gives available places and registration steps.','Présenter les résultats d’un atelier.','No results are discussed; the workshop is upcoming.','Annoncer une formation obligatoire.','The message offers places without making attendance mandatory.'],
 ['Une personne inscrite doit-elle se rendre dans une salle?','Non, elle participera à distance.','“Offert en ligne” and “aucun déplacement” support remote participation.','Oui, la salle sera annoncée vendredi.','Friday is the registration deadline; no room is promised.','Oui, sauf si son gestionnaire refuse.','The approval concerns registration, not the delivery format.']]);
add('training','B','Un apprentissage à partager',`Après le cours sur les tableaux de bord, chaque participant est invité à présenter un exemple utile à ses collègues. Cette présentation de dix minutes aura lieu pendant une réunion d’équipe. Il ne s’agit pas de reprendre tout le contenu du cours. Choisissez plutôt une méthode que vous avez déjà appliquée à un dossier. Les présentations commenceront en novembre.`,[
 ['Combien de temps doit durer la présentation?','Dix minutes.','The passage specifies “présentation de dix minutes”.','Une réunion entière.','The presentation takes place during the meeting, not throughout it.','Tout le mois de novembre.','November is the starting month, not the duration.'],
 ['Que souhaite-t-on surtout partager?','Une application concrète du cours.','“Une méthode… déjà appliquée” establishes the practical focus.','L’intégralité du contenu du cours.','“Il ne s’agit pas de reprendre tout le contenu” excludes that.','Une évaluation des formateurs.','The text requests an example, not a trainer evaluation.'],
 ['Quel exemple correspond à la demande?','Un tableau utilisé pour suivre les demandes de son service.','An example already used in a work file fits the stated purpose.','Une liste de tous les chapitres du cours.','A chapter list is a summary, not an applied method.','Une méthode que personne n’a encore essayée.','The text asks for a method the presenter has already applied.']]);
add('training','C','Au-delà du taux de participation',`Le taux de participation aux formations a augmenté cette année. Ce résultat est encourageant, mais il ne suffit pas à démontrer que les pratiques ont changé. Nous proposons donc un suivi trois mois après chaque activité, fondé sur des exemples d’utilisation des acquis. Ce suivi ne servirait pas à classer les employés : il permettrait plutôt d’ajuster l’offre aux besoins réels des équipes.`,[
 ['Quand le suivi proposé aurait-il lieu?','Trois mois après chaque activité.','The timing is explicitly “trois mois après chaque activité”.','Avant chaque inscription.','The proposal concerns post-training follow-up.','Uniquement à la fin de l’année.','“Chaque activité” rules out a single annual follow-up.'],
 ['Quelle idée défend le texte?','Évaluer l’utilisation des acquis, au-delà de la présence aux cours.','The contrast between participation and changed practices is the central argument.','Remplacer toutes les formations par des évaluations.','The author proposes adjusting training, not eliminating it.','Classer les employés selon leur assiduité.','The passage expressly rejects ranking employees.'],
 ['Comment l’auteur considère-t-il la hausse de participation?','Comme un signe positif, mais insuffisant à lui seul.','“Encourageant, mais… ne suffit pas” combines approval and qualification.','Comme la preuve définitive d’un changement de pratiques.','The author says the opposite: it is not enough to demonstrate change.','Comme un résultat sans aucun intérêt.','Calling it encouraging gives it some value.']]);
add('training','C','Une formule à adapter',`La formation autonome permet de progresser à son rythme. Encore faut-il que du temps lui soit réellement consacré. Sans plages protégées, les urgences risquent de la reléguer au second plan. Une formule mixte, associant modules individuels et échanges courts, pourrait limiter cet écueil. Elle ne serait toutefois pertinente que si les gestionnaires reconnaissent ces plages comme du temps de travail à part entière.`,[
 ['Quelle formule est envisagée?','Des modules individuels accompagnés de courts échanges.','The text explicitly defines the mixed format this way.','Uniquement des cours magistraux.','The proposed format includes autonomous modules.','Des échanges sans aucun module individuel.','Both elements are required in the stated proposal.'],
 ['Quelle condition est essentielle au succès de la formule?','Reconnaître et protéger le temps consacré à la formation.','“Encore faut-il” and the final condition make time protection central.','Supprimer toutes les urgences du service.','The text proposes protected time, not eliminating every emergency.','Permettre seulement l’apprentissage hors des heures de travail.','“Temps de travail à part entière” directly contradicts this.'],
 ['Que signifie « pourrait limiter cet écueil »?','La formule est une solution possible, sans garantie absolue.','“Pourrait” is conditional and “limiter” means reduce, not eliminate.','La formule éliminera certainement tout obstacle.','Neither certainty nor total elimination is expressed.','La formule a déjà échoué dans toutes les équipes.','No past trial or failure is reported.']]);
add('teamwork','B','Un relais pendant les congés',`Pendant l’absence de Samira, du 4 au 15 mai, Julien répondra aux demandes courantes. Les dossiers urgents seront transmis à la cheffe d’équipe. Avant son départ, Samira déposera un état d’avancement dans le dossier partagé. Merci de consulter ce document avant de joindre Julien : il contient les échéances et les coordonnées utiles.`,[
 ['Qui recevra les dossiers urgents?','La cheffe d’équipe.','Urgent files are explicitly assigned to the team lead.','Julien uniquement.','Julien handles routine requests; urgent files have a different recipient.','Samira pendant ses congés.','The message sets up coverage for her absence.'],
 ['À quoi sert ce message?','Organiser la continuité du travail pendant une absence.','It explains coverage, escalation, and the handover document.','Modifier définitivement les postes de l’équipe.','The arrangement is limited to the stated absence.','Annuler toutes les échéances.','Deadlines are documented, not cancelled.'],
 ['Que devrait faire un collègue qui cherche une échéance?','Consulter d’abord le dossier partagé.','The text asks colleagues to check the document before contacting Julien.','Appeler immédiatement Samira.','This bypasses the stated handover process.','Attendre le retour de Samira.','The shared document is intended to make waiting unnecessary.']]);
add('teamwork','B','Des réunions plus utiles',`À compter de lundi, notre rencontre hebdomadaire durera trente minutes. Envoyez vos points à l’ordre du jour le jeudi précédent. Chaque point doit préciser si une décision est attendue ou s’il s’agit simplement d’une information. Les documents longs seront lus avant la rencontre. Nous conserverons cinq minutes à la fin pour confirmer les responsabilités.`,[
 ['Quand faut-il envoyer les points à discuter?','Le jeudi précédent la rencontre.','The deadline is explicitly “le jeudi précédent”.','Pendant les cinq dernières minutes.','Those minutes are reserved for responsibilities.','Après la rencontre du lundi.','Points must be sent beforehand.'],
 ['Quel est l’objectif de ces changements?','Mieux préparer une réunion courte et orientée vers l’action.','Preparation, decision labels, and responsibilities support this purpose.','Éviter toute prise de décision.','The text specifically allows points requiring decisions.','Lire ensemble tous les documents longs.','Long documents are to be read before the meeting.'],
 ['Que doit préciser un point à l’ordre du jour?','Si une décision est nécessaire.','This is a stated requirement for each item.','Le nombre total de pages de tous les documents.','No such count is requested.','Le nom de tous les employés absents.','Attendance reporting is not discussed.']]);
add('teamwork','C','Une consultation plus représentative',`Les mêmes personnes prennent souvent la parole en réunion, ce qui peut donner l’impression d’un consensus plus large qu’il ne l’est. Recueillir des commentaires écrits en amont ne vise pas à réduire les échanges, mais à les enrichir. Il faudra néanmoins restituer les avis minoritaires dans la synthèse, faute de quoi le nouveau procédé reproduirait le biais qu’il cherche à corriger.`,[
 ['Que propose-t-on avant les réunions?','Recueillir des commentaires écrits.','“En amont” means beforehand and refers to written comments.','Supprimer les échanges oraux.','The passage explicitly says this is not the aim.','Faire voter uniquement les personnes les plus actives.','This would reinforce the stated problem and is not proposed.'],
 ['Quel problème cherche-t-on à résoudre?','Une impression de consensus qui ne reflète pas tous les avis.','The opening identifies unequal participation and a misleading consensus.','Un manque de documents administratifs.','The problem is representation, not paperwork volume.','L’absence complète d’opinions dans l’équipe.','Opinions exist; some are less audible.'],
 ['Pourquoi conserver les avis minoritaires dans la synthèse?','Pour éviter de reproduire le même biais.','“Faute de quoi… reproduirait le biais” directly links the two.','Pour leur donner automatiquement priorité sur tous les autres.','Representation does not imply automatic priority.','Pour montrer que le projet a forcément échoué.','The author gives a condition for success, not a declaration of failure.']]);
add('teamwork','C','La coopération se mesure autrement',`Le nombre de messages échangés entre services a doublé. On pourrait y voir une coopération accrue; pourtant, plusieurs demandes circulent encore sans responsable clairement désigné. Plutôt que de multiplier les canaux, nous gagnerions à définir les points de passage et les décisions attendues. La fluidité dépend moins du volume des échanges que de leur capacité à faire avancer les dossiers.`,[
 ['Quel indicateur a doublé?','Le nombre de messages entre services.','This is the stated quantitative change.','Le nombre de dossiers terminés.','Completion numbers are not provided.','Le nombre de responsables désignés.','The text instead identifies unclear responsibility.'],
 ['Que recommande l’auteur?','Clarifier les responsabilités et les décisions attendues.','Defined handoff points and expected decisions are the proposed improvement.','Créer toujours plus de canaux de communication.','“Plutôt que” explicitly contrasts this with the recommendation.','Cesser les échanges entre services.','The aim is more useful exchanges, not no exchanges.'],
 ['Quel jugement porte-t-il sur le volume de messages?','Il ne prouve pas à lui seul la qualité de la coopération.','The author questions the inference from quantity to cooperation.','Il démontre nécessairement une efficacité supérieure.','“Pourtant” introduces evidence against that conclusion.','Il est forcément nuisible dans toute situation.','The text does not condemn all messages; it questions the measure.']]);
add('projects','B','Une échéance reportée',`Le fournisseur livrera les données le 12 juin au lieu du 5 juin. La remise du rapport est donc reportée au 20 juin. Les travaux qui ne dépendent pas de ces données doivent se poursuivre selon le calendrier initial. Veuillez signaler à Nadia toute autre activité touchée par ce retard avant demain midi.`,[
 ['Quelle est la nouvelle date de remise du rapport?','Le 20 juin.','The report deadline is explicitly moved to June 20.','Le 12 juin.','This is the new data delivery date, not the report date.','Le 5 juin.','This is the original data delivery date.'],
 ['Quel est le principal objet du message?','Adapter le calendrier à un retard de livraison.','The message announces new dates and asks about affected activities.','Suspendre l’ensemble du projet.','Unaffected work must continue.','Changer de fournisseur immédiatement.','No supplier change is announced.'],
 ['Une tâche indépendante des données doit-elle attendre?','Non, elle doit suivre le calendrier initial.','The text expressly keeps unaffected work on schedule.','Oui, jusqu’au 20 juin.','That date applies to the report, not all work.','Oui, jusqu’à une nouvelle autorisation générale.','No such authorization requirement is stated.']]);
add('projects','B','Le suivi du budget',`Le tableau budgétaire doit être mis à jour chaque vendredi. Inscrivez les dépenses engagées, même si la facture n’a pas encore été reçue. Les montants estimés doivent être identifiés comme tels dans la colonne « Commentaires ». Si une dépense dépasse le montant prévu, ajoutez une courte explication et avisez la responsable du projet.`,[
 ['Faut-il inscrire une dépense engagée sans facture reçue?','Oui.','“Même si la facture n’a pas encore été reçue” explicitly includes it.','Non, il faut attendre le paiement.','Payment is not the criterion in the instructions.','Seulement à la fin du projet.','Updates are weekly.'],
 ['Quel est le but de ces consignes?','Maintenir un portrait budgétaire à jour et explicite.','Regular entries, estimate labels, and explanations support accurate tracking.','Interdire toute estimation.','Estimates are allowed if identified.','Remplacer la responsable du projet.','No staffing change appears.'],
 ['Que faire en cas de dépassement prévu?','L’expliquer et aviser la responsable.','Both actions are explicitly requested.','Effacer le montant initial.','The instructions do not authorize deleting the original amount.','Attendre de recevoir toutes les factures.','The process requires timely reporting of commitments.']]);
add('projects','C','Un projet pilote sous conditions',`Le comité appuie le lancement d’un projet pilote, sous réserve qu’un bilan intermédiaire soit présenté après six semaines. Cet appui ne préjuge pas de la généralisation du dispositif. Le bilan devra distinguer les gains attribuables au nouvel outil de ceux qui résultent du renfort temporaire de personnel. À défaut, une amélioration apparente pourrait conduire à une décision mal étayée.`,[
 ['Quelle condition accompagne l’appui du comité?','Présenter un bilan après six semaines.','“Sous réserve” introduces this condition.','Généraliser immédiatement le dispositif.','The text says support does not settle generalization.','Réduire le personnel avant le lancement.','A temporary staffing reinforcement is mentioned, not a required cut.'],
 ['Pourquoi distinguer l’effet de l’outil de celui du renfort?','Pour évaluer ce qui explique réellement les gains.','The distinction avoids attributing all improvement to the tool.','Pour prouver à l’avance que l’outil est inutile.','The evaluation is open; no failure is assumed.','Pour supprimer le bilan intermédiaire.','The distinction is a requirement within that review.'],
 ['Quelle est la position du comité?','Favorable à un essai, avec des exigences d’évaluation.','Support is conditional and limited to the pilot.','Définitivement favorable à une adoption générale.','“Ne préjuge pas” excludes that certainty.','Opposée à toute expérimentation.','The committee supports launching a pilot.']]);
add('projects','C','Un risque à rendre visible',`La marge prévue au calendrier a été presque entièrement absorbée par les validations initiales. La date finale reste atteignable, à condition que les arbitrages restants soient rendus cette semaine. Il serait trompeur de présenter le projet comme en retard; il serait tout aussi imprudent de le déclarer sans risque. Le rapport de suivi devrait expliciter cette dépendance plutôt que se limiter à un code de couleur.`,[
 ['Que faut-il obtenir cette semaine?','Les arbitrages restants.','The final date is conditional on those decisions this week.','Toutes les factures finales.','Invoices are not discussed.','Une nouvelle date de lancement obligatoire.','No mandatory new launch date is stated.'],
 ['Que devrait montrer le rapport?','La dépendance entre les décisions attendues et le respect du délai.','“Expliciter cette dépendance” is the central recommendation.','Seulement une couleur rassurante.','The author criticizes relying only on a colour.','Un retard déjà certain.','The final date is still attainable.'],
 ['Comment décrire l’état du projet?','Encore réalisable dans les délais, mais exposé à un risque précis.','The text rejects both certain delay and absence of risk.','Terminé et sans risque.','Remaining decisions show the project is not finished.','Impossible à terminer à la date prévue.','“Reste atteignable” explicitly contradicts this.']]);
add('telework','B','Joindre l’équipe à distance',`Les jours de télétravail, indiquez votre disponibilité dans le calendrier partagé. Pour une demande qui peut attendre, utilisez le courriel. Pour une urgence opérationnelle, téléphonez au numéro de service. La messagerie instantanée peut servir aux échanges rapides, mais elle ne remplace pas le registre des décisions, qui doit rester à jour.`,[
 ['Quel canal faut-il utiliser en cas d’urgence opérationnelle?','Le numéro de téléphone de service.','The text explicitly assigns emergencies to the service number.','Uniquement le courriel.','Email is for requests that can wait.','Le registre des décisions.','The register records decisions; it is not the emergency channel.'],
 ['Que précise le message?','Les usages des outils de communication à distance.','Each tool is assigned a purpose.','Une interdiction du télétravail.','Telework days are assumed to continue.','Un changement de salaire.','Pay is never discussed.'],
 ['Une décision prise par messagerie doit-elle être inscrite au registre?','Oui, le registre doit rester à jour.','Instant messaging does not replace the decision record.','Non, la messagerie remplace le registre.','The text expressly says the opposite.','Seulement si elle a été prise au bureau.','No location-based exception is given.']]);
add('telework','B','Réserver un poste de travail',`À partir du mois prochain, les employés de notre unité réserveront leur poste de travail au moyen de l’outil interne. Les réservations ouvriront deux semaines à l’avance. Si vous annulez votre présence, libérez le poste dès que possible pour qu’un collègue puisse l’utiliser. Pour un besoin d’équipement particulier, communiquez avec les services administratifs.`,[
 ['Quand les réservations ouvriront-elles?','Deux semaines à l’avance.','The booking window is explicitly stated.','Le jour même uniquement.','This contradicts the two-week window.','Après la journée de présence.','Reservations must precede use.'],
 ['Pourquoi libérer un poste en cas d’absence?','Pour permettre à un collègue de le réserver.','“Pour qu’un collègue puisse l’utiliser” provides the purpose.','Pour annuler toutes les réservations de l’unité.','The action applies only to the unused desk.','Pour éviter de communiquer avec son équipe.','Communication avoidance is not the stated aim.'],
 ['À qui adresser un besoin d’équipement particulier?','Aux services administratifs.','The final sentence names the contact.','À tous les collègues individuellement.','The passage gives a specific service contact.','Au fournisseur du calendrier.','No calendar provider is mentioned.']]);
add('telework','C','Une mesure à interpréter',`Les délais de réponse ont diminué pendant l’essai de travail hybride. Il serait cependant hâtif d’attribuer ce résultat au seul lieu de travail : l’équipe a également simplifié son circuit d’approbation. Une analyse par type de demande permettrait de mieux comprendre les gains. Elle devrait aussi tenir compte des dossiers complexes, dont le traitement peut être long sans être inefficace.`,[
 ['Quel autre changement a eu lieu pendant l’essai?','La simplification du circuit d’approbation.','The text says the team “a également simplifié” this process.','La suppression des dossiers complexes.','Those files still need to be considered.','L’arrêt des demandes reçues.','Response times were measured, so requests continued.'],
 ['Quelle analyse est recommandée?','Une analyse par type de demande, attentive à la complexité.','Both segmentation and complex files are specified.','Une comparaison limitée au lieu de travail.','The author warns against attributing results only to location.','Une mesure excluant tous les dossiers longs.','The text asks that complex files be included.'],
 ['Que dit le texte d’un traitement long?','Il peut être justifié par la complexité.','“Long sans être inefficace” explicitly allows this.','Il démontre toujours l’inefficacité.','The passage directly rejects this equivalence.','Il prouve que le télétravail est impossible.','No such general conclusion is drawn.']]);
add('telework','C','Préserver des temps communs',`La souplesse des horaires constitue un avantage réel. Elle peut néanmoins compliquer la coopération si les plages de disponibilité ne se recoupent jamais. Fixer quelques temps communs ne reviendrait pas nécessairement à uniformiser toutes les journées. L’enjeu serait de préserver assez de coordination pour que l’autonomie de chacun ne se traduise pas par des délais supplémentaires pour les autres.`,[
 ['Quelle difficulté est évoquée?','Des disponibilités qui ne se recoupent pas.','The risk arises when availability windows never overlap.','Des bureaux systématiquement fermés.','Office closures are not mentioned.','Une interdiction des horaires souples.','The passage recognizes flexibility as a benefit.'],
 ['Que cherche la proposition?','Concilier autonomie et coordination.','The final sentence states the balance the proposal seeks.','Rendre toutes les journées identiques.','The text explicitly says common times need not do that.','Supprimer tout temps collectif.','Some shared availability is proposed.'],
 ['Quel est le ton du texte?','Nuancé et orienté vers un compromis.','It acknowledges benefits and limits, then proposes a balance.','Hostile à toute forme d’autonomie.','Autonomy is preserved in the proposed approach.','Certain qu’aucune coordination n’est utile.','The passage argues for sufficient coordination.']]);
add('leadership','B','Préparer les entretiens',`Les entretiens de mi-année commenceront le 7 septembre. Avant votre rencontre, choisissez deux réalisations et une difficulté que vous souhaitez discuter. Il n’est pas nécessaire de rédiger un long rapport. Quelques notes suffisent. L’objectif est de faire le point sur vos besoins et de convenir des priorités pour les prochains mois.`,[
 ['Que faut-il préparer?','Deux réalisations et une difficulté.','This is the explicit preparation requested.','Un rapport détaillé de toutes les activités.','The text says a long report is unnecessary.','Une liste des erreurs des collègues.','The preparation concerns the employee’s own achievements and difficulty.'],
 ['Quel est l’objectif de l’entretien?','Faire le point et convenir des prochaines priorités.','The final sentence states that purpose.','Annoncer automatiquement une promotion.','No promotion is promised.','Évaluer uniquement la qualité d’un rapport écrit.','Notes are sufficient; the focus is discussion.'],
 ['Des notes courtes sont-elles acceptables?','Oui, elles suffisent.','“Quelques notes suffisent” makes this explicit.','Non, un long rapport est obligatoire.','The message expressly says it is not necessary.','Seulement après la rencontre.','Notes are requested before the meeting.']]);
add('leadership','B','Déléguer un mandat',`Je confie à Léa la coordination de la prochaine consultation. Elle pourra organiser les rencontres et répartir les tâches. Toute modification du budget devra toutefois être approuvée par moi. Nous ferons un point rapide chaque mardi. Les autres membres de l’équipe sont invités à lui transmettre leurs suggestions directement.`,[
 ['Qui doit approuver une modification du budget?','La personne qui écrit le message.','“Approuvée par moi” retains budget authority with the writer.','Léa seule.','Léa’s autonomy explicitly excludes budget changes.','N’importe quel membre de l’équipe.','No collective authorization is given.'],
 ['Que fait principalement ce message?','Préciser un mandat et ses limites.','It assigns coordination, actions, limits, and follow-up.','Retirer toutes les responsabilités de Léa.','She receives a coordination mandate.','Annuler la consultation.','The next consultation is being organized.'],
 ['Léa peut-elle organiser les rencontres sans nouvelle approbation mentionnée?','Oui, cette responsabilité lui est confiée.','“Elle pourra organiser les rencontres” explicitly grants this authority.','Non, seule la modification du budget est permise.','This reverses the stated permissions.','Non, aucune tâche ne lui est confiée.','Several tasks are expressly delegated.']]);
add('leadership','C','Reconnaître sans simplifier',`Mettre en valeur les résultats individuels peut soutenir la motivation. Encore faut-il éviter que la reconnaissance ne rende invisibles les contributions moins faciles à chiffrer, comme l’accompagnement des nouveaux collègues. Une démarche équitable ne consisterait pas à récompenser tout le monde de façon identique, mais à rendre explicites les critères et à diversifier les formes de contribution reconnues.`,[
 ['Quel exemple de contribution peu chiffrable est donné?','L’accompagnement des nouveaux collègues.','This example appears explicitly after “comme”.','Le total des factures payées.','This is not the example and is readily countable.','Le nombre de postes vacants.','Vacancies are not discussed.'],
 ['Que recommande le texte?','Clarifier les critères et reconnaître différentes contributions.','The final sentence names both actions.','Récompenser uniquement les résultats chiffrés.','That would preserve the problem the text identifies.','Attribuer obligatoirement la même récompense à tous.','The passage explicitly distinguishes equity from identical rewards.'],
 ['L’auteur rejette-t-il la reconnaissance individuelle?','Non, il en souligne l’utilité tout en posant des conditions.','“Peut soutenir” is positive; “encore faut-il” qualifies it.','Oui, il la juge toujours nuisible.','The opening states a possible motivational benefit.','Non, il la considère suffisante dans sa forme actuelle.','The author recommends changes to make it fairer.']]);
add('leadership','C','Décider après avoir écouté',`La consultation n’engage pas une gestionnaire à retenir chaque suggestion. Elle l’oblige toutefois à expliquer comment les avis ont éclairé sa décision, surtout lorsque celle-ci s’écarte de la préférence majoritaire. Sans ce retour, même une décision bien fondée risque d’être perçue comme arbitraire. La transparence porte donc autant sur le raisonnement que sur le résultat annoncé.`,[
 ['Que doit expliquer la gestionnaire selon le texte?','Comment les avis ont éclairé sa décision.','This is the stated responsibility after consultation.','Pourquoi elle retiendra nécessairement toutes les suggestions.','The opening explicitly denies that obligation.','Comment éviter de recevoir des suggestions.','The text presumes consultation has occurred.'],
 ['Quelle est l’idée principale?','Rendre le raisonnement visible après une consultation.','The conclusion emphasizes reasoning as well as the outcome.','Toujours suivre la majorité sans explication.','The text allows departing from the majority with explanation.','Annoncer seulement le résultat final.','The author says transparency extends beyond the result.'],
 ['Pourquoi expliquer une décision pourtant bien fondée?','Pour éviter qu’elle soit perçue comme arbitraire.','The text distinguishes the merits from how the decision may be perceived.','Pour prouver que tous les avis étaient identiques.','The passage explicitly contemplates divergent preferences.','Pour garantir que personne ne sera jamais déçu.','No guarantee of universal satisfaction is offered.']]);
add('conflict','B','Clarifier une situation',`Deux collègues ont signalé des attentes différentes concernant le partage des dossiers. Une rencontre est prévue jeudi pour clarifier les faits et convenir d’une méthode commune. Chaque personne est invitée à apporter un exemple précis. La discussion portera sur l’organisation du travail, et non sur la personnalité des participants.`,[
 ['Que doivent apporter les participants?','Un exemple précis.','This is the explicit request.','Une évaluation de la personnalité de l’autre.','The discussion expressly excludes personality.','Une décision déjà signée.','The method is to be agreed during the meeting.'],
 ['Quel est le but de la rencontre?','Clarifier les faits et organiser le partage du travail.','These are the two stated aims.','Désigner publiquement un coupable.','No blame or public sanction is proposed.','Annuler tous les dossiers.','The concern is how to share files, not ending them.'],
 ['Quelle intervention correspond au cadre annoncé?','Décrire un dossier reçu sans responsable désigné.','This is a concrete work-organization example.','Affirmer qu’un collègue a toujours mauvais caractère.','That assigns a personality trait, contrary to the stated scope.','Éviter tout exemple concret.','The message explicitly requests an example.']]);
add('conflict','B','Un accord à vérifier',`À la suite de notre échange, nous essaierons la nouvelle répartition des tâches pendant deux semaines. Chacun notera les difficultés rencontrées sans modifier seul la répartition. Nous nous retrouverons le 22 avril pour examiner les observations et décider des ajustements. Cet essai ne constitue pas encore une entente permanente.`,[
 ['Combien de temps durera l’essai?','Deux semaines.','The trial duration is stated directly.','Deux mois.','The text specifies weeks, not months.','De façon permanente dès maintenant.','The final sentence rules out permanence at this stage.'],
 ['Que prévoit le message?','Un essai suivi d’un examen commun.','The trial, observations, and review date form the plan.','Une répartition définitive sans révision.','Adjustments are explicitly to be considered.','Une modification individuelle quotidienne.','Participants must not change the allocation alone.'],
 ['Que faire si une difficulté apparaît pendant l’essai?','La noter pour l’examen commun.','The text asks each person to record difficulties.','Changer seul les tâches immédiatement.','This is explicitly prohibited.','Abandonner automatiquement tout l’accord.','No automatic cancellation is specified.']]);
add('conflict','C','Un désaccord qui renseigne',`Un désaccord persistant ne révèle pas forcément un manque de bonne volonté. Il peut signaler que deux équipes sont évaluées selon des objectifs incompatibles. Demander davantage de souplesse aux personnes ne suffirait alors pas : il faudrait aussi examiner les règles qui orientent leurs décisions. La médiation gagnerait à distinguer les tensions relationnelles des contradictions organisationnelles, sans nier leurs interactions.`,[
 ['Quelle cause possible de désaccord est évoquée?','Des objectifs d’évaluation incompatibles.','This cause is explicitly presented as a possibility.','L’absence certaine de bonne volonté.','The opening warns against assuming this.','Une interdiction de travailler ensemble.','No such rule is stated.'],
 ['Que recommande l’auteur?','Examiner aussi les règles et objectifs de l’organisation.','The argument broadens the response beyond individual flexibility.','Traiter uniquement les personnalités.','This ignores the organizational contradictions discussed.','Supprimer toute médiation.','The text proposes improving mediation, not removing it.'],
 ['Comment comprendre « sans nier leurs interactions »?','Les deux types de tensions sont distincts, mais peuvent s’influencer.','Distinguishing them does not make them independent.','Les tensions relationnelles et organisationnelles sont toujours identiques.','The author explicitly asks to distinguish them.','Les règles n’ont jamais d’effet sur les relations.','The phrase acknowledges interaction rather than denying it.']]);
add('conflict','C','Une entente limitée mais utile',`L’accord obtenu ne règle pas toutes les divergences sur la répartition des ressources. Il fixe néanmoins une procédure de consultation avant toute modification importante. Cette avancée reste modeste, mais elle réduit le risque de décisions perçues comme unilatérales. Sa portée dépendra de son application réelle : une consultation tenue après la décision viderait la procédure de son sens.`,[
 ['Quand la consultation doit-elle avoir lieu?','Avant toute modification importante.','The agreement explicitly requires consultation beforehand.','Uniquement après la décision.','The final sentence explains why that would undermine the process.','Après la disparition de toutes les divergences.','The process operates despite remaining disagreements.'],
 ['Quel est l’apport de l’accord?','Encadrer les changements malgré des divergences persistantes.','It establishes a procedure without resolving every disagreement.','Régler définitivement toutes les divergences.','The first sentence explicitly denies this.','Supprimer toute modification future.','The agreement regulates consultation before changes; it does not ban them.'],
 ['Quelle appréciation l’auteur formule-t-il?','Une avancée limitée, dont l’utilité dépend de l’application.','“Modeste” and “dépendra” express this measured judgment.','Une réussite totale et garantie.','Both the scope and implementation are qualified.','Une mesure sans aucun intérêt possible.','The text identifies a reduction in the risk of unilateral decisions.']]);
export { passages, questions as readingQuestions };
