import type { Vocabulary, OralPrompt, ThemeId } from '../types';
const vocab:Vocabulary[]=[];
function words(theme:ThemeId,rows:[string,string,string][]){rows.forEach(([french,english,example],i)=>vocab.push({id:`v-${theme}-${i+1}`,theme,french,english,example}))}
words('training',[
 ['une formation','training / a training course','Cette formation porte sur la rédaction claire.'],['un acquis','something learned / an acquired skill','Nous mettons nos acquis en pratique.'],['s’inscrire à','to register for','Je souhaite m’inscrire à cet atelier.'],['un apprentissage','learning','L’apprentissage demande du temps.'],['un perfectionnement','professional development','Le perfectionnement fait partie de mon plan.'],['une compétence','a skill','Cette activité développe une compétence utile.'],['un atelier','a workshop','L’atelier dure deux heures.'],['un besoin','a need','La formation répond à un besoin précis.'],['facultatif / facultative','optional','La séance est facultative.'],['obligatoire','mandatory','Ce module est obligatoire.'],['mettre à jour','to update','Il faut mettre à jour nos connaissances.'],['une inscription','registration','Mon inscription a été confirmée.'],['un suivi','follow-up','Un suivi aura lieu dans trois mois.'],['approfondir','to deepen / explore further','Je voudrais approfondir ce sujet.'],['mettre en pratique','to put into practice','Elle met en pratique une nouvelle méthode.']]);
words('teamwork',[
 ['répartir','to allocate / divide up','Nous allons répartir les tâches.'],['un compte rendu','meeting minutes / an account','Le compte rendu résume nos décisions.'],['un relais','a handover / coverage','Julien assure le relais pendant mon absence.'],['une échéance','a deadline','Chaque dossier a une échéance.'],['un dossier partagé','a shared folder','Le document est dans le dossier partagé.'],['entraide','mutual support','L’entraide facilite notre travail.'],['convenir de','to agree on','Nous devons convenir des prochaines étapes.'],['une contribution','a contribution','Chaque contribution compte.'],['un ordre du jour','an agenda','Veuillez lire l’ordre du jour.'],['en amont','beforehand / upstream','Les avis sont recueillis en amont.'],['un avis','an opinion / view','Je souhaite connaître votre avis.'],['un consensus','a consensus','Un consensus semble se dégager.'],['minoritaire','held by a minority','Cet avis minoritaire mérite d’être entendu.'],['un biais','a bias','Le procédé risque de créer un biais.'],['collaborer','to collaborate','Nos services collaborent sur ce dossier.']]);
words('projects',[
 ['un jalon','a milestone','Le prochain jalon est prévu en juin.'],['un livrable','a deliverable','Le rapport est notre principal livrable.'],['reporter','to postpone','Nous devons reporter la réunion.'],['un délai','a timeframe / delay','Le délai de traitement a diminué.'],['un dépassement','an overrun','Tout dépassement doit être expliqué.'],['une dépense engagée','a committed expense','La dépense engagée figure au tableau.'],['un bilan','a review / assessment','Le bilan présente les résultats du pilote.'],['sous réserve de','subject to','Le projet est approuvé sous réserve de validation.'],['un arbitrage','a decision between competing priorities','Un arbitrage est nécessaire cette semaine.'],['étayer','to substantiate','Des données permettent d’étayer la conclusion.'],['une marge','a margin / buffer','Le calendrier comprend une marge.'],['un risque','a risk','Le rapport décrit le risque principal.'],['un renfort','additional support / reinforcement','Un renfort temporaire a été accordé.'],['atteignable','achievable','La date finale reste atteignable.'],['un calendrier','a schedule','Nous avons ajusté le calendrier.']]);
words('telework',[
 ['le télétravail','remote work','Le télétravail demande une bonne coordination.'],['une plage horaire','a time slot','Nous avons une plage horaire commune.'],['une disponibilité','availability','Indiquez votre disponibilité dans le calendrier.'],['se recouper','to overlap','Nos horaires se recoupent le matin.'],['un poste de travail','a workstation / desk','J’ai réservé un poste de travail.'],['une réservation','a booking','Pensez à annuler votre réservation.'],['libérer','to free up / release','Je vais libérer le bureau réservé.'],['un circuit d’approbation','an approval process','Le circuit d’approbation a été simplifié.'],['la souplesse','flexibility','La souplesse des horaires est appréciée.'],['à distance','remotely','Nous participons à distance.'],['un registre','a register / log','La décision est inscrite au registre.'],['tenir compte de','to take into account','Il faut tenir compte de la complexité.'],['hâtif / hâtive','hasty / premature','Cette conclusion serait hâtive.'],['uniformiser','to standardize','Il n’est pas nécessaire d’uniformiser les horaires.'],['une coordination','coordination','Une coordination régulière reste nécessaire.']]);
words('leadership',[
 ['déléguer','to delegate','La gestionnaire sait déléguer.'],['un mandat','an assignment / mandate','Le mandat précise les résultats attendus.'],['une attente','an expectation','Les attentes doivent être claires.'],['la reconnaissance','recognition','La reconnaissance soutient la motivation.'],['équitable','fair / equitable','Nous cherchons une démarche équitable.'],['un critère','a criterion','Chaque critère sera expliqué.'],['éclairer','to inform / shed light on','Les avis ont éclairé la décision.'],['une réalisation','an achievement','Présentez deux réalisations récentes.'],['faire le point','to take stock','L’entretien permet de faire le point.'],['une priorité','a priority','Nous avons défini trois priorités.'],['l’autonomie','autonomy','L’autonomie s’accompagne de responsabilités.'],['arbitraire','arbitrary','Une décision inexpliquée peut sembler arbitraire.'],['la transparence','transparency','La transparence renforce la confiance.'],['s’écarter de','to depart from','La décision s’écarte de la proposition initiale.'],['rendre explicite','to make explicit','Il faut rendre explicite le raisonnement.']]);
words('conflict',[
 ['un désaccord','a disagreement','Un désaccord peut révéler un problème de fond.'],['un terrain d’entente','common ground','Nous cherchons un terrain d’entente.'],['clarifier','to clarify','Commençons par clarifier les faits.'],['un malentendu','a misunderstanding','Cette précision évite un malentendu.'],['une divergence','a difference of opinion','Certaines divergences persistent.'],['une médiation','mediation','La médiation facilite le dialogue.'],['la bonne volonté','goodwill','La bonne volonté ne résout pas tout.'],['une entente','an agreement','L’entente sera revue dans deux semaines.'],['unilatéral / unilatérale','unilateral','Évitons une décision unilatérale.'],['une portée','scope / significance','La portée de cet accord reste limitée.'],['un ajustement','an adjustment','Nous déciderons des ajustements ensemble.'],['apaiser','to ease / calm','L’écoute peut apaiser les tensions.'],['une contradiction','a contradiction','Les objectifs présentent une contradiction.'],['une période d’essai','a trial period','Une période d’essai est prévue.'],['remettre en question','to question / reconsider','Les résultats nous amènent à remettre en question la méthode.']]);
export const vocabulary=vocab;
const oral:OralPrompt[]=[];
function prompts(theme:ThemeId,rows:[string,string][]){rows.forEach(([prompt,guidance],i)=>oral.push({id:`o-${theme}-${i+1}`,theme,level:i<2?'B':'C',prompt,guidance}))}
prompts('training',[
 ['Décrivez une formation qui vous a aidé dans votre travail.','B: Set the context, explain what you learned, and give a concrete example of using it. Use the past tense for the course and the present for its current benefit.'],
 ['Comment choisissez-vous une activité de perfectionnement?','B: Describe your usual steps and explain two practical criteria. Use d’abord, ensuite, enfin to guide the listener.'],
 ['Dans quelle mesure la formation autonome peut-elle remplacer les échanges avec un formateur?','C: Take a position, distinguish situations, weigh a limitation, and conclude with conditions for success. Try certes… toutefois.'],
 ['Comment évalueriez-vous l’utilité d’une formation au-delà du taux de participation?','C: Propose evidence, explain what it would show, and acknowledge a measurement limitation. Use the conditional for your proposal.']]);
prompts('teamwork',[
 ['Racontez une situation où vous avez aidé un collègue à terminer une tâche.','B: Explain the task, your contribution, and the result. Keep the sequence clear and distinguish your actions from your colleague’s.'],
 ['Comment votre équipe organise-t-elle le travail pendant les congés?','B: Describe responsibilities, handover information, and one example. Explain why the arrangement helps.'],
 ['Une équipe doit-elle toujours rechercher le consensus avant de décider?','C: Define when consensus helps, discuss time or accountability constraints, and defend a balanced position with an example.'],
 ['Comment feriez-vous pour que les avis moins souvent exprimés soient pris en compte?','C: Propose a method, explain the expected effect, and identify a risk in its implementation. Link the proposal to a concrete workplace situation.']]);
prompts('projects',[
 ['Décrivez un projet auquel vous avez participé récemment.','B: State the goal, your role, the main steps, and a result. Use a specific example rather than a list of duties.'],
 ['Que faites-vous lorsqu’une échéance risque de ne pas être respectée?','B: Explain how you check the situation, inform others, and suggest a next step. Give a practical example.'],
 ['Dans quelles circonstances serait-il préférable de reporter un projet plutôt que d’en réduire la portée?','C: Compare consequences, identify decision criteria, and qualify your recommendation. Explain a hypothetical example.'],
 ['Comment distingueriez-vous une amélioration durable d’un résultat lié à des ressources temporaires?','C: Explain a comparison method, possible confounding factors, and the limits of your conclusion. Use si clauses accurately.']]);
prompts('telework',[
 ['Décrivez votre façon de communiquer avec vos collègues à distance.','B: Describe the tools, when you use each, and an example of a useful exchange.'],
 ['Comment préparez-vous une journée de travail au bureau?','B: Explain the sequence, what you reserve or bring, and how you coordinate with others.'],
 ['La souplesse des horaires est-elle toujours compatible avec les besoins d’une équipe?','C: Weigh autonomy and coordination, distinguish types of work, and propose conditions for a balanced arrangement.'],
 ['Quels éléments examineriez-vous avant de conclure qu’une formule hybride améliore la productivité?','C: Identify several indicators, explain their limits, and consider alternative explanations. Avoid equating speed alone with quality.']]);
prompts('leadership',[
 ['Décrivez une occasion où votre gestionnaire a clarifié vos priorités.','B: Explain the initial situation, what was clarified, and how it affected your work.'],
 ['Quelles qualités appréciez-vous chez une personne qui dirige une équipe?','B: Choose two qualities and support each with a concrete example. Explain the effect on the team.'],
 ['Comment concilieriez-vous la reconnaissance individuelle et la valorisation du travail collectif?','C: Discuss a tension, propose fair criteria, and explain how you would include less visible contributions.'],
 ['Une gestionnaire peut-elle prendre une décision contraire à l’avis majoritaire après une consultation?','C: State a position, discuss responsibility and transparency, and give conditions that make the decision defensible.']]);
prompts('conflict',[
 ['Racontez un malentendu professionnel que vous avez réussi à clarifier.','B: Set the context, describe the clarification, and explain the outcome without assigning personal blame.'],
 ['Comment préparez-vous une discussion sur un partage de tâches qui vous préoccupe?','B: Explain the facts you gather, what you want to understand, and how you propose a next step.'],
 ['Dans quelle mesure un conflit peut-il révéler un problème d’organisation plutôt qu’un problème personnel?','C: Distinguish causes, show how they interact, and support your argument with a hypothetical example.'],
 ['Une entente qui ne règle pas toutes les divergences peut-elle être une réussite?','C: Define success, weigh the limits of a partial agreement, and explain what follow-up would make it useful.']]);
export const oralPrompts=oral;
