import type { Theme } from '../types';
export const themes: Theme[] = [
 {id:'training',title:'Training',french:'Apprendre au travail.',description:'Training requests, professional development, and putting new skills to work.',lessons:[
 {title:'Find the condition before you act',explanation:'A workplace message often gives a condition before an action. Repérez « à condition de », « sous réserve de » and « avant de ». They tell you what must happen first. In writing, pour is followed by an infinitive when the subject stays the same.',example:'Pour suivre cette formation, vous devez obtenir l’accord de votre gestionnaire.',translation:'To take this training, you must obtain your manager’s approval.'},
 {title:'Purpose and concession',explanation:'Pour que introduces a purpose with a conjugated verb in the subjunctive. Bien que also takes the subjunctive and signals a concession: something remains true despite another fact. Do not turn a recommendation into a requirement when reading.',example:'Bien que la formation soit facultative, elle est recommandée pour que chacun puisse utiliser le nouvel outil.',translation:'Although the training is optional, it is recommended so that everyone can use the new tool.'}]},
 {id:'teamwork',title:'Teamwork',french:'Avancer ensemble.',description:'Shared responsibilities, useful feedback, and clear handovers.',lessons:[
 {title:'Who does what?',explanation:'Identify the person responsible for each action. Nous, vous and leur can refer to different groups in a message. An indirect object introduced by à becomes lui or leur; it does not agree with the object being sent.',example:'Les collègues attendent le compte rendu. Je leur envoie le document cet après-midi.',translation:'The colleagues are waiting for the minutes. I am sending them the document this afternoon.'},
 {title:'Make the connection',explanation:'Toutefois introduces a limitation; par conséquent introduces a result. Distinguishing those links helps you follow the argument. In writing, the past participle with avoir agrees with a direct object placed before the verb.',example:'Les tâches que nous avons réparties seront revues vendredi; toutefois, les responsables restent les mêmes.',translation:'The tasks we allocated will be reviewed on Friday; however, the people responsible remain the same.'}]},
 {id:'projects',title:'Projects',french:'Du plan à l’action.',description:'Milestones, deadlines, budgets, and the decisions behind them.',lessons:[
 {title:'Read dates precisely',explanation:'D’ici vendredi sets a deadline. Depuis describes something that began in the past and continues. Pendant gives a duration. A postponement changes the date; a cancellation ends the activity. Check which one the text actually says.',example:'Le projet se poursuit depuis mars. Le rapport doit être remis d’ici vendredi.',translation:'The project has been ongoing since March. The report must be submitted by Friday.'},
 {title:'Conditions and consequences',explanation:'For a hypothetical present or future situation, use si + imparfait, then the conditional. For an unreal past situation, use si + plus-que-parfait, then the past conditional. A risk described as possible is not a confirmed outcome.',example:'Si nous avions reçu les données plus tôt, nous aurions terminé l’analyse.',translation:'If we had received the data earlier, we would have finished the analysis.'}]},
 {id:'telework',title:'Telework',french:'Travailler autrement.',description:'Work arrangements, availability, and effective communication at a distance.',lessons:[
 {title:'Separate rules from suggestions',explanation:'Il faut and devoir express an obligation. Il est conseillé de expresses advice. Pouvoir expresses possibility or permission. Notice whether a rule applies to everyone or just one team.',example:'Il est conseillé de réserver un bureau; les visiteurs doivent toutefois s’inscrire à l’accueil.',translation:'Booking a desk is recommended; visitors must nevertheless register at reception.'},
 {title:'Read a balanced argument',explanation:'Certes… mais… acknowledges one point before qualifying it. Ne… que means only, not a full negation. Conditional forms can soften a proposal without making it an established policy.',example:'Certes, le travail à distance facilite la concentration, mais il ne convient qu’à certaines tâches.',translation:'Admittedly, remote work makes concentration easier, but it is suitable only for certain tasks.'}]},
 {id:'leadership',title:'Leadership',french:'Donner le cap.',description:'Delegation, fair decisions, recognition, and leading through change.',lessons:[
 {title:'Understand the purpose',explanation:'A message can inform, invite, request, or announce a decision. Look at its main action rather than a single detail. In polite requests, pourriez-vous is less direct than devez-vous.',example:'Pourriez-vous proposer deux priorités pour notre prochaine rencontre?',translation:'Could you suggest two priorities for our next meeting? '},
 {title:'Keep the nuance',explanation:'A nuanced argument can support a measure while limiting its scope. Pour autant does not mean automatically. Dont replaces a phrase introduced by de, including avoir besoin de and être responsable de.',example:'L’autonomie dont l’équipe a besoin ne dispense pas la gestionnaire de préciser les attentes.',translation:'The autonomy the team needs does not relieve the manager of clarifying expectations.'}]},
 {id:'conflict',title:'Conflict resolution',french:'Trouver un terrain d’entente.',description:'Clarifying concerns, listening carefully, and agreeing on next steps.',lessons:[
 {title:'Describe facts without assigning blame',explanation:'Neutral language describes an observable event rather than a person’s character. Avant de and après avoir place actions in order. A meeting to clarify facts does not imply that a complaint has already been upheld.',example:'Avant de proposer une solution, nous allons clarifier les attentes de chacun.',translation:'Before suggesting a solution, we will clarify everyone’s expectations.'},
 {title:'Disagree constructively',explanation:'Bien que concedes a point; à moins que introduces an exception and takes the subjunctive. A proposal in the conditional is not a promise. Read both what an agreement resolves and what it leaves open.',example:'Bien que nos points de vue diffèrent, nous pourrions convenir d’une période d’essai.',translation:'Although our views differ, we could agree on a trial period.'}]}];
