import type { Level, Question, ThemeId } from '../types';
type Item=[string,string,string,string,string,string,string,string];
const questions:Question[]=[];
function bank(theme:ThemeId,level:Level,rows:Item[]){rows.forEach(([objective,prompt,correct,why,bad1,why1,bad2,why2])=>{const n=questions.length;const shift=n%3;const options=[correct,bad1,bad2],explanations=[why,why1,why2];for(let j=0;j<shift;j++){options.push(options.shift()!);explanations.push(explanations.shift()!)}questions.push({id:`w-${theme}-${questions.filter(q=>q.theme===theme).length+1}`,theme,level,skill:'writing',objective,prompt,options,answer:(3-shift)%3,explanations})})}
bank('training','B',[
 ['Prepositions','Elle s’est inscrite ___ un cours de rédaction.','à','S’inscrire à is the required construction.','de','De does not introduce the course after s’inscrire.','pour de','Pour de is not a grammatical combination here.'],
 ['Verb forms','Nous ___ la formation demain matin.','suivrons','The future of suivre for nous is suivrons.','suivront','Suivront agrees with ils or elles, not nous.','suivrez','Suivrez agrees with vous, not nous.'],
 ['Agreement','Cette formation est très ___.','utile','Utile has the same spelling in masculine and feminine singular.','utiles','The adjective modifies singular formation.','utilité','Utilité is a noun; an adjective is required after est très.'],
 ['Vocabulary','Veuillez ___ le formulaire avant vendredi.','remplir','Remplir un formulaire means to complete a form.','remplissage','A noun cannot follow veuillez in this construction.','remplissez','Veuillez takes an infinitive, not another imperative.'],
 ['Cohesion','Le cours est complet. ___, vous pouvez vous inscrire sur la liste d’attente.','Toutefois','Toutefois introduces the remaining possibility despite the course being full.','Parce que','Parce que would leave a dependent clause with no main clause.','Afin de','Afin de must be followed by an infinitive, not vous pouvez.'],
 ['Agreement','Quelle section contient une erreur? « Les nouveaux employés / participe à la formation / chaque lundi. »','participe à la formation','The plural subject requires participent.','Les nouveaux employés','The determiner, adjective, and noun agree in the plural.','chaque lundi','Chaque correctly takes a singular noun.'],
 ['Register','Quelle demande est formulée de manière polie et correcte?','Pourriez-vous confirmer mon inscription?','The conditional politely asks for confirmation.','Vous confirmer mon inscription?','This lacks a conjugated verb.','Pourriez-vous confirmez mon inscription?','Pourriez-vous must be followed by the infinitive confirmer.']]);
bank('training','C',[
 ['Subjunctive','Il faut que chaque participant ___ le module.','termine','Il faut que requires the subjunctive; termine is correct for a singular subject.','terminera','The future indicative does not follow il faut que here.','terminent','This plural form does not agree with chaque participant.'],
 ['Subjunctive','Bien que le cours ___ facultatif, il est recommandé.','soit','Bien que takes the subjunctive.','est','Est is indicative, not subjunctive.','sera','The future indicative is not appropriate after bien que.'],
 ['Pronouns','Les compétences ___ nous avons besoin seront abordées.','dont','Avoir besoin de requires dont.','que','Que would replace a direct object; besoin takes de.','où','Où refers to a place or time, not the object of besoin de.'],
 ['Agreement','Les méthodes que la formatrice a ___ sont utiles.','présentées','The preceding direct object méthodes is feminine plural.','présenté','With avoir, agreement is required when the direct object precedes.','présentés','The object is feminine, so the masculine plural is incorrect.'],
 ['Verb forms','Si j’avais reçu l’invitation, je ___ inscrit.','me serais','An unreal past condition takes the past conditional in the result.','me serai','This is future perfect, not past conditional.','m’étais','The plus-que-parfait does not express the hypothetical result here.'],
 ['Cohesion','La formation est accessible, ___ les participants disposent d’une connexion.','pourvu que','Pourvu que introduces a condition and takes the subjunctive.','malgré','Malgré requires a noun phrase, not this conjugated clause.','afin de','Afin de requires an infinitive.'],
 ['Agreement','Quelle section contient une erreur? « Les ressources / que nous avons consulté / sont à jour. »','que nous avons consulté','Consultées must agree with the preceding feminine plural object ressources.','Les ressources','This noun phrase is correctly formed.','sont à jour','Sont agrees with ressources; à jour is invariable.']]);
bank('teamwork','B',[
 ['Pronouns','Les collègues attendent le document. Je ___ envoie une copie.','leur','Envoyer à des personnes uses the indirect object pronoun leur.','leurs','The pronoun leur never takes s.','les','Les would be a direct object pronoun; the copy is the direct object.'],
 ['Agreement','Les tâches sont bien ___.','réparties','The adjective agrees with feminine plural tâches.','répartis','This is masculine plural.','répartie','The singular does not agree with tâches.'],
 ['Verb forms','Vous ___ présenter le dossier lundi.','devez','Devez agrees with vous and takes an infinitive.','doivent','Doivent agrees with ils or elles.','dois','Dois agrees with je or tu.'],
 ['Prepositions','Merci de répondre ___ vos collègues.','à','Répondre à quelqu’un takes à.','de','Répondre de means to answer for something, not reply to a person.','chez','Chez marks a location associated with a person.'],
 ['Vocabulary','Nous devons ___ les responsabilités avant de commencer.','préciser','Préciser means to clarify and fits the infinitive construction.','précision','A noun cannot follow devons here.','précises','This is not an infinitive.'],
 ['Agreement','Quelle section contient une erreur? « Notre équipe / travaillent ensemble / sur ce dossier. »','travaillent ensemble','Équipe is singular and requires travaille.','Notre équipe','Notre correctly agrees with the singular noun.','sur ce dossier','This prepositional phrase is correct.'],
 ['Cohesion','Karim est absent; ___, Aline assurera le suivi.','par conséquent','The replacement is a consequence of his absence.','bien que','Bien que cannot introduce this future indicative main clause.','afin de','Afin de needs an infinitive, not Aline assurera.']]);
bank('teamwork','C',[
 ['Agreement','Les décisions que l’équipe a ___ seront communiquées.','prises','The preceding direct object décisions is feminine plural.','pris','The participle must agree with the preceding direct object.','prise','A singular participle does not agree with décisions.'],
 ['Pronouns','Voici la collègue ___ je vous ai parlé.','dont','Parler de quelqu’un is represented by dont.','que','The object is introduced by de, so que is not suitable.','où','Où is used for place or time.'],
 ['Subjunctive','Il est essentiel que nous ___ les informations.','partagions','The subjunctive of partager for nous is partagions.','partageons','This is present indicative.','partagerons','This is future indicative.'],
 ['Verb forms','Si les rôles étaient clairs, nous ___ du temps.','gagnerions','Si + imparfait pairs with the present conditional here.','gagnerons','The future does not match this hypothetical condition.','gagnions','This is the imperfect, not the conditional result.'],
 ['Cohesion','___ leurs avis divergent, ils ont trouvé un compromis.','Bien que','Bien que introduces a concession; divergent is also the subjunctive form.','Malgré','Malgré cannot directly introduce this finite clause.','En dépit','En dépit needs de followed by a noun phrase.'],
 ['Agreement','Quelle section contient une erreur? « Chacun des membres / ont reçu / le compte rendu. »','ont reçu','The subject chacun is singular, so use a reçu.','Chacun des membres','Chacun de + plural group is grammatical.','le compte rendu','This noun phrase is correctly singular.'],
 ['Register','Quelle phrase exprime une réserve de façon professionnelle?','Cette option mérite d’être examinée, mais ses coûts restent à préciser.','The sentence acknowledges merit and states a specific limitation.','Cette option mérite de examinée.','The passive infinitive d’être examinée is needed.','Les coûts de cette option reste à préciser.','The plural subject coûts requires restent.']]);
bank('projects','B',[
 ['Prepositions','Le projet est en cours ___ janvier.','depuis','Depuis marks an action that began in the past and continues.','pendant','Pendant marks a duration, not a starting month in this sentence.','envers','Envers describes an attitude toward someone.'],
 ['Verb forms','Nous ___ le rapport hier.','avons envoyé','The passé composé fits the completed event yesterday.','enverrons','The future conflicts with hier.','envoyons demain','Demain conflicts with hier and changes the time reference.'],
 ['Agreement','Les nouvelles dates sont ___.','confirmées','Dates is feminine plural, requiring confirmées.','confirmé','This is masculine singular.','confirmée','This is feminine singular.'],
 ['Vocabulary','Le rapport doit être remis avant la date ___.','limite','Date limite is the established expression for a deadline.','limiter','An infinitive cannot modify date this way.','limitation','Date limitation is not the correct expression.'],
 ['Prepositions','Nous devons terminer le travail ___ vendredi au plus tard.','d’ici','D’ici sets a deadline.','depuis','Depuis marks a past starting point, not a deadline.','durant de','This combination is ungrammatical.'],
 ['Agreement','Quelle section contient une erreur? « Les dépenses / dépasse le budget / prévu. »','dépasse le budget','The plural subject dépenses requires dépassent.','Les dépenses','This plural noun phrase is correct.','prévu','Prévu agrees with masculine singular budget.'],
 ['Cohesion','Les données manquent. ___, nous devons attendre avant de conclure.','Donc','Donc introduces the consequence of missing data.','Même si','Même si creates an incomplete subordinate sentence here.','Pour','Pour cannot introduce this conjugated clause.']]);
bank('projects','C',[
 ['Verb forms','Si le fournisseur avait confirmé la date, nous ___ le calendrier.','aurions ajusté','An unreal past condition takes the past conditional.','aurons ajusté','This is future perfect, not past conditional.','avons ajusté','The passé composé would assert a completed fact, not this hypothetical result.'],
 ['Subjunctive','Le comité exige que le bilan ___ prêt lundi.','soit','Exiger que requires the subjunctive.','est','The indicative is not correct after this demand.','sera','The future indicative is not correct here.'],
 ['Pronouns','Le risque ___ nous devons tenir compte est important.','dont','Tenir compte de requires dont.','que','Que would replace a direct object; this expression takes de.','lequel','Lequel alone does not supply the required de.'],
 ['Agreement','Les sommes que nous avons ___ couvrent l’essai.','prévues','Sommes is the preceding feminine plural direct object.','prévu','Agreement is required with the preceding object.','prévus','This is masculine plural; sommes is feminine.'],
 ['Cohesion','Le lancement aura lieu, ___ toutes les validations soient terminées.','à condition que','This expresses a condition and takes the subjunctive.','malgré','Malgré requires a noun phrase.','grâce à','Grâce à also requires a noun phrase, not this clause.'],
 ['Agreement','Quelle section contient une erreur? « Les données / ont été vérifié / par l’analyste. »','ont été vérifié','In this passive form, vérifiées agrees with données.','Les données','This noun phrase is correctly plural.','par l’analyste','Par correctly introduces the agent.'],
 ['Vocabulary','Il faut ___ entre les deux options avant de lancer l’achat.','trancher','Trancher entre means to decide between alternatives.','tranchant','A present participle cannot follow il faut here.','tranche','The infinitive, not a conjugated form, is required.']]);
bank('telework','B',[
 ['Prepositions','Elle travaille ___ distance deux jours par semaine.','à','À distance is the established expression.','de','De distance is not the phrase for working remotely.','en','En distance is not standard in this expression.'],
 ['Verb forms','Si vous êtes absent, ___ votre réservation.','annulez','The imperative for vous is annulez.','annulent','This agrees with ils, not an imperative addressed to vous.','annules','This is a tu form, not vous.'],
 ['Agreement','La connexion est ___.','stable','Stable agrees with a feminine singular subject without changing form.','stables','The adjective must be singular.','stabilité','Stabilité is a noun, not the adjective required here.'],
 ['Pronouns','Le bureau est libre. Vous pouvez ___ utiliser.','l’','Utiliser takes a direct object; le becomes l’ before a vowel.','lui','Lui is an indirect object pronoun.','leur','Leur refers to indirect plural recipients.'],
 ['Vocabulary','Veuillez ___ votre disponibilité dans le calendrier.','indiquer','Veuillez takes an infinitive; indiquer fits the meaning.','indication','This noun cannot follow veuillez.','indiquez','A second imperative cannot follow veuillez directly.'],
 ['Agreement','Quelle section contient une erreur? « Les postes disponibles / est réservés / aux visiteurs. »','est réservés','The plural subject requires sont réservés.','Les postes disponibles','All three words agree in the plural.','aux visiteurs','À + les correctly contracts to aux.'],
 ['Cohesion','La demande n’est pas urgente; vous pouvez ___ répondre demain.','donc','Donc connects the lack of urgency to the later response.','malgré','Malgré cannot act as an adverb between pouvez and répondre.','afin','Afin must be followed by de or que in a purpose construction.']]);
bank('telework','C',[
 ['Subjunctive','Il est préférable que vous ___ votre disponibilité.','précisiez','Il est préférable que takes the subjunctive.','précisez','Précisez is indicative or imperative, not subjunctive.','préciserez','The future is not appropriate after this expression.'],
 ['Pronouns','L’outil ___ nous nous servons sera remplacé.','dont','Se servir de requires dont.','que','Que cannot replace the de complement.','où','Où would refer to a location or time.'],
 ['Agreement','Les plages que nous avons ___ conviennent à tous.','retenues','The preceding direct object plages is feminine plural.','retenu','The participle must agree with the preceding object.','retenus','The masculine plural does not agree with plages.'],
 ['Verb forms','Si les horaires se recoupaient, les échanges ___ plus simples.','seraient','A hypothetical condition in the imperfect takes the conditional result.','seront','The future does not fit this hypothetical pairing.','sont été','Sont été is not a valid verb form.'],
 ['Cohesion','La mesure ne concerne ___ les employés de cette unité.','que','Ne… que restricts the scope to only these employees.','aucun','Aucun cannot precede the definite plural phrase this way.','rien','Rien cannot serve as a determiner before les employés.'],
 ['Agreement','Quelle section contient une erreur? « Les modalités / de cet essai / sera révisées en juin. »','sera révisées en juin','The plural subject requires seront révisées.','Les modalités','This plural noun phrase is correct.','de cet essai','Cet is correctly used before masculine essai beginning with a vowel.'],
 ['Register','Quelle proposition est correcte et nuancée?','Nous pourrions fixer une plage commune, sans uniformiser tous les horaires.','The conditional makes a proposal and the second phrase limits its scope.','Nous pourrions fixons une plage commune.','Pourrions requires the infinitive fixer.','Nous pourrait fixer une plage commune.','Nous requires pourrions, not pourrait.']]);
bank('leadership','B',[
 ['Verb forms','La gestionnaire ___ les priorités demain.','présentera','The singular future agrees with gestionnaire and demain.','présenteront','This plural future form does not agree with the singular subject gestionnaire.','présenterons','This is the nous form, not the form for la gestionnaire.'],
 ['Prepositions','Merci ___ votre contribution.','de','Merci de + noun is correct here.','à de','These prepositions cannot combine here.','envers','Envers does not introduce thanks in this construction.'],
 ['Agreement','Les attentes doivent être ___.','claires','Attentes is feminine plural.','clair','Masculine singular does not agree.','claire','Feminine singular does not agree with a plural subject.'],
 ['Pronouns','Léa coordonne le projet. Nous ___ transmettons nos suggestions.','lui','Transmettre à Léa uses the indirect pronoun lui.','la','La is a direct object pronoun; suggestions is the direct object.','elle','A subject pronoun cannot appear in this object position.'],
 ['Vocabulary','Nous allons ___ les priorités ensemble.','définir','Allons takes an infinitive, and définir means to set or define.','définition','A noun cannot follow allons in this future construction.','définissons','The conjugated nous form cannot follow allons.'],
 ['Agreement','Quelle section contient une erreur? « Chaque employé / préparent deux exemples / avant l’entretien. »','préparent deux exemples','Chaque employé is singular and requires prépare.','Chaque employé','Chaque correctly takes a singular noun.','avant l’entretien','The temporal prepositional phrase is correct.'],
 ['Register','Quelle demande est correcte et courtoise?','Pourriez-vous préciser les attentes?','The conditional request is grammatical and polite.','Pourriez-vous précisez les attentes?','Pourriez-vous takes the infinitive préciser.','Vous pourriez précisions les attentes?','Précisions cannot follow pourriez; an infinitive is required.']]);
bank('leadership','C',[
 ['Subjunctive','Il importe que les critères ___ explicites.','soient','Il importe que requires the subjunctive plural soient.','sont','Sont is indicative.','seront','Seront is future indicative.'],
 ['Pronouns','L’autonomie ___ elle dispose est importante.','dont','Disposer de requires dont.','que','Que does not replace the de complement.','où','Où cannot represent the abstract object of disposer de here.'],
 ['Agreement','Les contributions qu’il a ___ méritent d’être reconnues.','soulignées','Contributions is the preceding feminine plural direct object.','souligné','The preceding object requires agreement.','soulignés','The masculine plural does not agree with contributions.'],
 ['Verb forms','Si nous avions expliqué les critères, l’équipe ___ mieux compris la décision.','aurait','The result of an unreal past condition takes the past conditional aurait compris.','aura','Aura compris is future perfect.','avait','Avait compris is plus-que-parfait, not the hypothetical result here.'],
 ['Cohesion','La consultation est utile; elle ne garantit pas ___ l’unanimité.','pour autant','Pour autant qualifies what does not automatically follow from usefulness.','afin de','Afin de requires an infinitive, not l’unanimité.','parce que','Parce que must introduce a clause, not this noun alone.'],
 ['Agreement','Quelle section contient une erreur? « Les critères / que nous avons défini / sont publics. »','que nous avons défini','Définis agrees with preceding masculine plural critères.','Les critères','The noun phrase is correct.','sont publics','Publics correctly agrees with critères.'],
 ['Vocabulary','Une décision doit être ___ par des éléments vérifiables.','étayée','Étayer means to support with evidence; the participle agrees with décision.','étayer','The passive être requires a past participle.','étayés','This masculine plural form does not agree with décision.']]);
bank('conflict','B',[
 ['Prepositions','Nous discuterons ___ la répartition des tâches.','de','Discuter de introduces the topic of discussion.','à','Discuter à does not introduce a topic.','chez','Chez marks a location, not the topic.'],
 ['Verb forms','Chaque personne ___ un exemple précis.','apportera','The singular future agrees with chaque personne.','apporteront','This future form is plural.','apporterons','This is the nous form.'],
 ['Agreement','Les observations sont ___.','utiles','The adjective agrees with plural observations.','utile','A singular adjective does not agree.','utilité','A noun cannot fill this adjective position.'],
 ['Vocabulary','Avant de conclure, il faut ___ les faits.','vérifier','Il faut takes an infinitive; vérifier fits checking facts.','vérification','This noun cannot introduce les faits in this construction.','vérifiez','This imperative cannot follow il faut directly.'],
 ['Cohesion','Les avis diffèrent. ___, une solution commune reste possible.','Toutefois','Toutefois introduces a possibility despite the disagreement.','Parce que','This would create an incomplete subordinate clause.','Malgré','Malgré requires a noun phrase, not this full clause.'],
 ['Agreement','Quelle section contient une erreur? « Les deux collègues / accepte la proposition / pour deux semaines. »','accepte la proposition','The plural subject requires acceptent.','Les deux collègues','The plural noun phrase is correct.','pour deux semaines','This phrase correctly expresses the duration.'],
 ['Register','Quelle phrase décrit un fait de façon neutre?','Le dossier m’a été transmis après la date convenue.','It describes an observable timing issue without a character judgment.','Tu es toujours irresponsable.','This is a personal generalization, not a neutral description of a fact.','Personne ne fait jamais aucun effort ici.','This sweeping judgment does not identify a specific event.']]);
bank('conflict','C',[
 ['Subjunctive','Bien que nos avis ___ différents, nous cherchons un accord.','soient','Bien que requires the subjunctive plural.','sont','Sont is indicative.','seront','Seront is future indicative.'],
 ['Pronouns','Le problème ___ nous parlons concerne deux équipes.','dont','Parler de requires dont.','que','The verb construction needs de, not a direct relative object.','où','Où represents place or time, not the topic here.'],
 ['Agreement','Les solutions que nous avons ___ seront testées.','proposées','The preceding direct object solutions is feminine plural.','proposé','The participle must agree with the preceding object.','proposés','The masculine plural does not agree with solutions.'],
 ['Verb forms','Si les attentes étaient explicites, nous ___ ces malentendus.','éviterions','Si + imparfait pairs with the conditional éviterions.','éviterons','The future does not fit this hypothetical construction.','évité','A past participle alone cannot serve as the conjugated verb.'],
 ['Subjunctive','L’essai se poursuivra à moins qu’un problème majeur ___.','survienne','À moins que takes the subjunctive; survienne is correct.','survient','Survient is indicative.','surviendra','Surviendra is future indicative.'],
 ['Agreement','Quelle section contient une erreur? « La procédure / a été approuvée / par les deux responsable. »','par les deux responsable','The noun after les deux must be plural: responsables.','La procédure','The singular feminine noun phrase is correct.','a été approuvée','The passive participle correctly agrees with procédure.'],
 ['Cohesion','L’accord reste limité; il constitue ___ une avancée.','néanmoins','Néanmoins concedes the limitation while recognizing progress.','afin que','Afin que introduces a clause, not the noun phrase une avancée.','malgré de','Malgré de is not grammatical here.']]);
export const writingQuestions=questions;
